app:
  build: app
  cap_add:
   - SYS_RAWIO
  devices:
   - /dev/mem
  links:
   - server
server:
  build: server
  ports:
   - "7890:7890"
  privileged: true
  volumes:
   - /dev/bus/usb:/dev/bus/usb
